version: '3.4'

services:
  abstractrest:
    image: starbucksrest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
